name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out your code
      - uses: actions/checkout@v3

      # 2️⃣ Install system dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git zip unzip openjdk-17-jdk

      # 3️⃣ Install Buildozer & Cython
      - name: Install Buildozer & Cython
        run: |
          pip3 install --upgrade buildozer cython

      # 4️⃣ Force-accept all Android SDK licenses
      - name: Accept Android SDK licenses
        run: |
          # Ensure the SDK is downloaded
          buildozer android sdk --yes
          # Accept every license
          yes | ${HOME}/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses || true

      # 5️⃣ Build the APK
      - name: Build APK
        run: |
          buildozer --verbose android debug

      # 6️⃣ Upload the .apk as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk
